######################################################################
############################## 公共配置 ##############################
######################################################################

server:
  servlet:
    contextPath: /web

############################ 下面是springBoot配置 ############################
spring:
  application:
    #项目名称
    name: web
  profiles: #开发/测试/生产环境分别对应dev/test/prod，可以自由定义
    active: dev      #开发环境
#    active: test     #测试环境
#    active: prod     #生产环境

mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: cn.bejwt.sesame.entity

############################ 上面是springBoot配置 ############################

############################ 下面是用户自定义配置 ############################
application:

############################ 上面是用户自定义配置 ############################